# Generated by Django 5.2.1 on 2025-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlist',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='restaurantlist',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='restaurantlist',
            name='title_ru',
        ),
    ]
