# Generated by Django 5.2.1 on 2025-05-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_remove_restaurantlist_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='category',
        ),
        migrations.AlterField(
            model_name='productdrinks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_drinks', to='restaurant_app.product'),
        ),
        migrations.AlterField(
            model_name='productextras',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_extras', to='restaurant_app.product'),
        ),
        migrations.AlterField(
            model_name='productingradient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingradient', to='restaurant_app.product'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_images', to='restaurant_app.aboutrestaurant'),
        ),
        migrations.AlterField(
            model_name='sellerimage',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_images', to='restaurant_app.bestsellers'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='category',
            field=models.ManyToManyField(to='restaurant_app.category'),
        ),
    ]
