# Generated by Django 5.2.1 on 2025-05-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_remove_mainmenu_category_alter_productdrinks_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='product',
        ),
        migrations.AlterField(
            model_name='interiorimage',
            name='interior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='restaurant_app.moderninterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_product', to='restaurant_app.category'),
        ),
    ]
